### ISSUE TITLE
chore: Adding code coverage badge

### ISSUE THREAD

**Issue by olleolleolle** [socketry/protocol-websocket#1]
The neighbouring project has a code coverage percentage badge on it.

Perhaps this project could, too?

**Comment by ioquatix** [comment]
Yes good idea

**Comment by ioquatix** [comment]
I've circled around on this issue, and I've decided to avoid adding badges, the only one I have now is the GitHub Actions status. Maybe even that is superfluous. Badges look great but are a bit of a pointless overhead for a README when it's presented elsewhere on the repo.
