### ISSUE TITLE
Ruby 2.7 ... args syntax while gemspec requires 2.5

### ISSUE THREAD

**Issue by Nakilon** [socketry/protocol-websocket#13]
This https://github.com/socketry/protocol-websocket/blob/249288dd8cd97b1ceec07c8a7e8c9162747f2f0d/lib/protocol/websocket/connection.rb#L64
while gemspec only requires 2.5
Can we avoid this syntax or edit the gemspec as 0.11.1 maybe?

**Comment by ioquatix** [comment]
Yeah, let's update the gemspec.
