### ISSUE TITLE
Not properly masking payload data on frame initialization?

### ISSUE THREAD

**Issue by masterful** [socketry/protocol-websocket#21]
Hello friends!

I was running into a little bit of fun with connections to an upstream server that validated `pong` frame payloads.

It looks like the PingFrame's PongFrame construction passes in the unpacked payload, but when I inspect the traffic that's being sent upstream I'm not seeing that payload get properly masked. I think this is because the PingFrame doesn't properly mask the payload when it's passed into the initializer. Following the code:
https://github.com/socketry/protocol-websocket/blob/main/lib/protocol/websocket/ping_frame.rb#L18

That will pass in the ping packet's (unpacked) payload as the payload argument to the pong frame. However, other frame constructions will leverage the `pack` method to ensure the mask is properly applied to the payload. Indeed, when I add the `pack` call immediately after that frame construction, it does properly encode the payload (and thus my temperamental server is happy again).
```ruby
# Generate a suitable reply.
# @returns [PongFrame]
def reply(**options)
  frame = PongFrame.new(true, self.unpack, **options)
  frame.pack(self.unpack)
```

I wanted to modify the frame initializer to properly pack the payload - but my naive approach was having issues - so I figured I'd make the issue first in case you were able to immediately see the issue. ❤️ 

Thank you again!!

**Comment by ioquatix** [comment]
IIRC the goal here was to avoid calling pack when the response should just be round tripped, but indeed it looks like it's not correctly encoding the payload. I agree, something like what you suggest makes sense.

**Comment by ioquatix** [comment]
Fixed in 76e7bc0c93c145eb361415006264d9df0108fdb6 and released in v0.19.1

**Comment by ioquatix** [comment]
A few notes about masking.

Client -> Server masking is the only required if the server also requires it. Technically it's required by the RFCs but at least I don't enforce it. The reason for the client to use masking is if a hostile server decides to use a WebSocket to break insecure proxies. It only really matters when dealing with clear-text connections and non-conforming proxy servers. Therefore, I don't think we should spent a huge amount of effort following the RFC to the letter here. If clients want to be especially defensive, they should use masking. But it does not protect the server in any way.

**Comment by masterful** [comment]
Holy smokes that was fast!
<img src="https://media1.giphy.com/media/nqYXNf3aK6EvK/giphy.gif"/>

Yeah - I also tried disabling masking but the server (which I don't have control over) did _not_ like that.

_SUPER_ appreciate the quick response and patch on this one - as well as a bit more background on what masking is for ❤️
